version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/technobd.com/public_html
hooks:
  BeforeInstall:
    - location: scripts/cleanup_old_files.sh  # Cleanup script
      runas: root
  AfterInstall:
    - location: scripts/install_dependencies.sh  # Install dependencies
      runas: root
    - location: scripts/set_permissions.sh  # New script to set permissions
      runas: root
    - location: scripts/restart_server.sh  # Restart server
      runas: root
