version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/technobd.com/public_html
    overwrite: true  # This will allow overwriting existing files
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      runas: root
  AfterInstall:
    - location: scripts/restart_server.sh
      runas: root
